

name: Pmd-Scan
on: [push]
jobs:
  apex:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup PMD
      uses: legetz/setup-pmd@7.0.0-rc3
    - name: APEX full scan
      run: pmd check --dir ./project-force/pf-app/main/default/classes/*.cls --rulesets ./config/pmd-ruleset.xml --no-fail-on-violation -f sarif -D -r pmd-report.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pmd-report.sarif
